# Verify the unmodified, pinned subset; native builds need no network checkout.
set(stx_bodft_root "${CMAKE_CURRENT_LIST_DIR}/../third_party/bfft")
file(READ "${stx_bodft_root}/provenance.json" stx_bodft_manifest)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${stx_bodft_root}/provenance.json")
string(JSON stx_bodft_count LENGTH "${stx_bodft_manifest}" sha256_lf)
math(EXPR stx_bodft_last "${stx_bodft_count} - 1")
foreach(index RANGE 0 ${stx_bodft_last})
  string(JSON path MEMBER "${stx_bodft_manifest}" sha256_lf ${index})
  string(JSON expected GET "${stx_bodft_manifest}" sha256_lf "${path}")
  file(READ "${stx_bodft_root}/${path}" contents)
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${stx_bodft_root}/${path}")
  string(REPLACE "\r\n" "\n" contents "${contents}")
  string(SHA256 actual "${contents}")
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Pinned BODFT source differs: ${path}")
  endif()
endforeach()
