#!/usr/bin/env python3
"""Generate the pinned Unicode grapheme tables and conformance cases."""

from __future__ import annotations

import argparse
import hashlib
import pathlib
import re
from dataclasses import dataclass

UNICODE_VERSION = "17.0.0"
EXPECTED_HASHES = {
    "grapheme": "d6b51d1d2ae5c33b451b7ed994b48f1f4dc62b2272a5831e7fd418514a6bae89",
    "derived": "24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08",
    "emoji": "2cb2bb9455cda83e8481541ecf5b6dfda66a3bb89efa3fa7c5297eccf607b72b",
    "test": "e2d134d2c52919bace503ebb6a551c1855fe1a1faec18478c78fff254a1793ec",
}

GCB_NAMES = [
    "CR", "LF", "Control", "Extend", "ZWJ", "Regional_Indicator",
    "Prepend", "SpacingMark", "L", "V", "T", "LV", "LVT",
]


@dataclass(frozen=True)
class Range:
    first: int
    last: int
    value: str


def digest(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def verify(path: pathlib.Path, role: str) -> None:
    actual = digest(path)
    if actual != EXPECTED_HASHES[role]:
        raise SystemExit(
            f"{path}: SHA-256 {actual} does not match pinned {EXPECTED_HASHES[role]}"
        )
    header = path.read_text(encoding="utf-8", errors="replace")[:512]
    expected_version = "17.0" if role == "emoji" else UNICODE_VERSION
    if expected_version not in header:
        raise SystemExit(f"{path}: does not identify Unicode {expected_version}")


def code_range(field: str) -> tuple[int, int]:
    parts = field.strip().split("..")
    first = int(parts[0], 16)
    return first, int(parts[-1], 16)


def parse_gcb(path: pathlib.Path) -> list[Range]:
    result: list[Range] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        body = line.split("#", 1)[0].strip()
        if not body:
            continue
        fields = [field.strip() for field in body.split(";")]
        if len(fields) == 2 and fields[1] in GCB_NAMES:
            first, last = code_range(fields[0])
            result.append(Range(first, last, fields[1]))
    return merge_ranges(result)


def parse_incb(path: pathlib.Path) -> list[Range]:
    result: list[Range] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        body = line.split("#", 1)[0].strip()
        if not body:
            continue
        fields = [field.strip() for field in body.split(";")]
        if len(fields) == 3 and fields[1] == "InCB" and fields[2] != "None":
            first, last = code_range(fields[0])
            result.append(Range(first, last, fields[2]))
    return merge_ranges(result)


def parse_extended_pictographic(path: pathlib.Path) -> list[Range]:
    result: list[Range] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        body = line.split("#", 1)[0].strip()
        if not body:
            continue
        fields = [field.strip() for field in body.split(";")]
        if len(fields) == 2 and fields[1] == "Extended_Pictographic":
            first, last = code_range(fields[0])
            result.append(Range(first, last, "Yes"))
    return merge_ranges(result)


def merge_ranges(ranges: list[Range]) -> list[Range]:
    ranges.sort(key=lambda item: (item.first, item.last))
    merged: list[Range] = []
    for item in ranges:
        if merged and item.first <= merged[-1].last:
            raise SystemExit(f"overlapping generated ranges: {merged[-1]} and {item}")
        if merged and item.value == merged[-1].value and item.first == merged[-1].last + 1:
            prior = merged[-1]
            merged[-1] = Range(prior.first, item.last, item.value)
        else:
            merged.append(item)
    return merged


def render_ranges(name: str, ranges: list[Range], enum_prefix: str) -> str:
    return (
        f"inline constexpr std::array {name} = {{\n"
        f"    UnicodeRange<{enum_prefix}>{{{hex(ranges[0].first)}, {hex(ranges[0].last)}, "
        f"{enum_prefix}::{ranges[0].value}}},\n"
        + "\n".join(
            f"    UnicodeRange<{enum_prefix}>{{{hex(item.first)}, {hex(item.last)}, "
            f"{enum_prefix}::{item.value}}},"
            for item in ranges[1:]
        )
        + "\n};\n"
    )


def write_tables(output: pathlib.Path, gcb: list[Range], incb: list[Range],
                 pictographic: list[Range], sources: dict[str, pathlib.Path]) -> None:
    preamble = f"""// Generated by tools/unicode/generate_grapheme_tables.py. DO NOT EDIT.
// Unicode {UNICODE_VERSION}; source SHA-256:
// GraphemeBreakProperty.txt {digest(sources['grapheme'])}
// DerivedCoreProperties.txt {digest(sources['derived'])}
// emoji-data.txt {digest(sources['emoji'])}
#pragma once

#include <array>
#include <cstdint>

namespace gui_forms::unicode_data {{

inline constexpr char version[] = "{UNICODE_VERSION}";

enum class GraphemeBreak : std::uint8_t {{
  Other, CR, LF, Control, Extend, ZWJ, Regional_Indicator, Prepend,
  SpacingMark, L, V, T, LV, LVT,
}};

enum class IndicConjunctBreak : std::uint8_t {{ None, Consonant, Extend, Linker }};

template <typename Value> struct UnicodeRange final {{
  char32_t first;
  char32_t last;
  Value value;
}};

"""
    pictographic_ranges = [Range(item.first, item.last, "Yes") for item in pictographic]
    bool_rows = "\n".join(
        f"    UnicodeRange<bool>{{{hex(item.first)}, {hex(item.last)}, true}},"
        for item in pictographic_ranges
    )
    content = (
        preamble
        + render_ranges("grapheme_break_ranges", gcb, "GraphemeBreak")
        + "\n"
        + render_ranges("indic_conjunct_break_ranges", incb, "IndicConjunctBreak")
        + "\ninline constexpr std::array extended_pictographic_ranges = {\n"
        + bool_rows
        + "\n};\n\n} // namespace gui_forms::unicode_data\n"
    )
    output.write_text(content, encoding="utf-8")


def parse_test_cases(path: pathlib.Path) -> list[tuple[int, list[int], list[int]]]:
    result: list[tuple[int, list[int], list[int]]] = []
    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        body = line.split("#", 1)[0].strip()
        if not body:
            continue
        tokens = body.split()
        codepoints: list[int] = []
        boundaries: list[int] = []
        scalar_index = 0
        for token in tokens:
            if token == "÷":
                boundaries.append(scalar_index)
            elif token == "×":
                continue
            elif re.fullmatch(r"[0-9A-F]+", token):
                codepoints.append(int(token, 16))
                scalar_index += 1
            else:
                raise SystemExit(f"{path}:{line_number}: unexpected token {token}")
        result.append((line_number, codepoints, boundaries))
    return result


def write_tests(output: pathlib.Path, cases: list[tuple[int, list[int], list[int]]],
                source: pathlib.Path) -> None:
    codepoints: list[int] = []
    boundaries: list[int] = []
    records: list[str] = []
    for line, points, breaks in cases:
        point_start = len(codepoints)
        break_start = len(boundaries)
        codepoints.extend(points)
        boundaries.extend(breaks)
        records.append(
            f"    {{{line}, {point_start}, {len(points)}, {break_start}, {len(breaks)}}},"
        )
    point_rows = "\n".join(
        "    " + ", ".join(hex(value) for value in codepoints[index:index + 12]) + ","
        for index in range(0, len(codepoints), 12)
    )
    break_rows = "\n".join(
        "    " + ", ".join(str(value) for value in boundaries[index:index + 24]) + ","
        for index in range(0, len(boundaries), 24)
    )
    content = f"""// Generated by tools/unicode/generate_grapheme_tables.py. DO NOT EDIT.
// GraphemeBreakTest-{UNICODE_VERSION}.txt SHA-256 {digest(source)}
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace gui_forms::unicode_test_data {{
struct GraphemeBreakCase final {{
  std::uint32_t source_line;
  std::uint32_t codepoint_offset;
  std::uint16_t codepoint_count;
  std::uint32_t boundary_offset;
  std::uint16_t boundary_count;
}};

inline constexpr std::array codepoints = {{
{point_rows}
}};
inline constexpr std::array<std::uint16_t, {len(boundaries)}> boundaries = {{
{break_rows}
}};
inline constexpr std::array<GraphemeBreakCase, {len(cases)}> cases = {{{{
{chr(10).join(records)}
}}}};
}} // namespace gui_forms::unicode_test_data
"""
    output.write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--grapheme", type=pathlib.Path, required=True)
    parser.add_argument("--derived", type=pathlib.Path, required=True)
    parser.add_argument("--emoji", type=pathlib.Path, required=True)
    parser.add_argument("--test", type=pathlib.Path, required=True)
    parser.add_argument("--tables-output", type=pathlib.Path, required=True)
    parser.add_argument("--tests-output", type=pathlib.Path, required=True)
    args = parser.parse_args()
    sources = {name: getattr(args, name) for name in EXPECTED_HASHES}
    for role, path in sources.items():
        verify(path, role)
    args.tables_output.parent.mkdir(parents=True, exist_ok=True)
    args.tests_output.parent.mkdir(parents=True, exist_ok=True)
    write_tables(args.tables_output, parse_gcb(args.grapheme), parse_incb(args.derived),
                 parse_extended_pictographic(args.emoji), sources)
    write_tests(args.tests_output, parse_test_cases(args.test), args.test)


if __name__ == "__main__":
    main()
