set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)
set(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)

find_program(GUI_FORMS_MINGW_C_COMPILER NAMES x86_64-w64-mingw32-gcc REQUIRED)
execute_process(COMMAND ${GUI_FORMS_MINGW_C_COMPILER} -print-sysroot
    OUTPUT_VARIABLE GUI_FORMS_MINGW_SYSROOT OUTPUT_STRIP_TRAILING_WHITESPACE
    COMMAND_ERROR_IS_FATAL ANY)
if(GUI_FORMS_MINGW_SYSROOT)
    list(APPEND CMAKE_FIND_ROOT_PATH "${GUI_FORMS_MINGW_SYSROOT}")
    if(IS_DIRECTORY "${GUI_FORMS_MINGW_SYSROOT}/x86_64-w64-mingw32")
        list(APPEND CMAKE_FIND_ROOT_PATH "${GUI_FORMS_MINGW_SYSROOT}/x86_64-w64-mingw32")
    endif()
endif()
list(REMOVE_DUPLICATES CMAKE_FIND_ROOT_PATH)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
