# Pass to the provider AND consumer: -DCMAKE_TOOLCHAIN_FILE=.../llvm22.cmake.
# CC/CXX names intentionally match ccache's content-checked compiler identity.
find_program(_gf_clang NAMES clang REQUIRED)
find_program(_gf_clangxx NAMES clang++ REQUIRED)
set(CMAKE_C_COMPILER "${_gf_clang}" CACHE FILEPATH "LLVM C driver")
set(CMAKE_CXX_COMPILER "${_gf_clangxx}" CACHE FILEPATH "LLVM C++ driver")
set(CMAKE_OBJCXX_COMPILER "${_gf_clangxx}" CACHE FILEPATH "LLVM Objective-C++ driver")
if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
    execute_process(COMMAND xcrun --show-sdk-path OUTPUT_VARIABLE _gf_sdk
                    OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    set(CMAKE_OSX_SYSROOT "${_gf_sdk}" CACHE PATH "Selected Xcode SDK")
    set(CMAKE_OSX_ARCHITECTURES arm64 CACHE STRING "Supported Apple architecture")
    set(CMAKE_OSX_DEPLOYMENT_TARGET 14.0 CACHE STRING "Minimum supported macOS")
    if(NOT DEFINED ENV{GUI_FORMS_LLVM_RUNTIME})
        message(FATAL_ERROR "Set GUI_FORMS_LLVM_RUNTIME to the LLVM 22.1.8 macOS 14 runtime prefix")
    endif()
    file(TO_CMAKE_PATH "$ENV{GUI_FORMS_LLVM_RUNTIME}" _gf_runtime)
    set(_gf_cxx "-stdlib=libc++ -nostdinc++ -isystem \"${_gf_runtime}/include/c++/v1\"")
    set(CMAKE_CXX_FLAGS_INIT "${_gf_cxx}")
    set(CMAKE_OBJCXX_FLAGS_INIT "${_gf_cxx}")
    set(_gf_link "-L\"${_gf_runtime}/lib\" -Wl,-rpath,\"${_gf_runtime}/lib\" -lunwind")
    set(CMAKE_EXE_LINKER_FLAGS_INIT "${_gf_link}")
    set(CMAKE_SHARED_LINKER_FLAGS_INIT "${_gf_link}")
    set(CMAKE_MODULE_LINKER_FLAGS_INIT "${_gf_link}")
endif()
